#!/bin/bash

usage() {
  echo "Usage: wmh_seg -i <input_file> -o <output_file> [-g] [-pmb] [-v] [-b <batch_size>] [--fast]"
  echo "Example: wmh_seg -i FLAIR.nii -o FLAIR_wmh.nii"
  echo "Example: wmh_seg -i FLAIR.nii -o FLAIR_wmh.nii -g -v -b 4"
  exit 1
}

input_file=""
output_file=""
use_gpu="False"
enable_pmb="False"
verbose="False"
batch=1
fast_mode="False"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -i)
      input_file=$2
      shift 2
      ;;
    -o)
      output_file=$2
      shift 2
      ;;
    -g)
      use_gpu="True"
      shift
      ;;
    -p)
      enable_pmb="True"
      shift
      ;;
    -v)
      verbose="True"
      shift
      ;;
    -b)
      batch=$2
      shift 2
      ;;
    --fast)
      fast_mode="True"
      shift
      ;;
    *)
      usage
      ;;
  esac
done

if [[ -z $input_file || -z $output_file ]]; then
  echo "Error: Missing input or output path."
  usage
fi

echo "Input file: $input_file"
echo "Output file: $output_file"
echo "Use GPU: $use_gpu"
echo "Enable PMB: $enable_pmb"
echo "Verbose mode: $verbose"
echo "Inference batch size: $batch"
echo "Fast mode: $fast_mode"

# Run wmh_pytorch.py script only if input and output paths are provided
if [[ -n $input_file && -n $output_file ]]; then
  wmh_pytorch.py "$input_file" "$output_file" "$use_gpu" "$wmh_seg_home" "$verbose" "$enable_pmb" "$batch" "$fast_mode"
fi
